### ISSUE TITLE
Three consecutive fail between sucess

### ISSUE THREAD

**Issue by abenevaut** [neilalbrock/sentry-bitbucket#5]
Here a little stacktrace coming between two tickets successfully send to bitbucket.
- I made a first ticket then sending it succefully
- I made a second that failed three time with the following stacktrace
- I tried it again and it finally send my second ticket to bitbucket

``` shell
    Internal Server Error: /cavaencoreparlerdebitsfr/cvepdb-site/group/21/actions/bitbucket/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/handlers/base.py", line 113, in get_response
        response = callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/decorators.py", line 164, in wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/decorators.py", line 117, in _wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/frontend/groups.py", line 563, in group_plugin_action
        response = plugin.get_view_response(request, group)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/plugins/base.py", line 323, in get_view_response
        response = self.view(request, group)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/plugins/bases/issue.py", line 174, in view
        request=request,
      File "/usr/local/lib/python2.7/dist-packages/sentry_bitbucket/plugin.py", line 105, in create_issue
        return data['local_id']
    KeyError: 'local_id'
    Internal Server Error: /cavaencoreparlerdebitsfr/cvepdb-site/group/21/actions/bitbucket/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/handlers/base.py", line 113, in get_response
        response = callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/decorators.py", line 164, in wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/decorators.py", line 117, in _wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/frontend/groups.py", line 563, in group_plugin_action
        response = plugin.get_view_response(request, group)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/plugins/base.py", line 323, in get_view_response
        response = self.view(request, group)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/plugins/bases/issue.py", line 174, in view
        request=request,
      File "/usr/local/lib/python2.7/dist-packages/sentry_bitbucket/plugin.py", line 105, in create_issue
        return data['local_id']
    KeyError: 'local_id'
    Internal Server Error: /cavaencoreparlerdebitsfr/cvepdb-site/group/5/actions/bitbucket/
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/handlers/base.py", line 113, in get_response
        response = callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/decorators.py", line 164, in wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/decorators.py", line 117, in _wrapped
        return func(request, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/web/frontend/groups.py", line 563, in group_plugin_action
        response = plugin.get_view_response(request, group)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/plugins/base.py", line 323, in get_view_response
        response = self.view(request, group)
      File "/usr/local/lib/python2.7/dist-packages/sentry-6.4.4-py2.7.egg/sentry/plugins/bases/issue.py", line 174, in view
        request=request,
      File "/usr/local/lib/python2.7/dist-packages/sentry_bitbucket/plugin.py", line 105, in create_issue
        return data['local_id']
    KeyError: 'local_id'
```

**Comment by dcramer** [comment]
Will dig into this. If I had to guess I'd say we're not handling some kind of error response from Bitbucket.

**Comment by dcramer** [comment]
I've fixed this in our fork if you want to pull in the changes, but will be releasing HEAD of getsentry/sentry-bitbucket to getsentry.com
